### ISSUE TITLE
reconcile the UCAN keypair API with `keystore-idb`

### ISSUE THREAD

**Issue by nichoth** [fission-suite/ucan#2]
The `ucans` library has a method `ucan.keypair.create`, which returns a keypair object with a `.did` method. In real life you would want to use the `keystore-idb` library though to manage persistent keys over time. However, the keystore-idb library returns a different API for a keypair. I started by forking the keystore-idb repo [here](https://github.com/nichoth/keystore-idb/blob/e48c81cb7368e5131a13735d18eb1d9465d081bf/test-tape/index.js#L9); this gives a method `getKeypair` that should return the same API that is returned by `ucans`.

It uses a different test library and bundler though, so not ideal for merging at this point

**Comment by matheus23** [comment]
I think the `Keypair` type in this library is very elegant.
* it doesn't require an exportable key (e.g. no `privateKey: Uint8Array` property or similar)
* it doesn't depend on the WebCrypto API.

That's why I think it's a great candidate for an interface between webnative and the ucans library.

A `@fission/keypair` library might be redundant. I think we'd rather support the `Keypair` type (or a conversion into it) in either `webnative` or `keystore-idb`.

**Comment by dholms** [comment]
Side note on this: 
> I will note in your code that Ed25519 keys and webcrypto elliptic curve keys (NIST 256 in this case) are not the same curve and so do not translate to one another. Webcrypto does not implement Ed25519 yet.

I am planning to implement both secp256k1 & the NIST curves in this library in the relatively short term, so that will give even better compatibility with `keystore-idb` (which uses the NIST curves)

**Comment by matheus23** [comment]
I think we can close this issue and continue tracking this in keystore-idb instead.
